-- ============================================================
-- GLOW BOXES - Deprecated migration: admin role policies
-- ============================================================
-- Security policies now live in database/policies.sql.
-- Run files in this order for the current production-ready setup:
--   1. database/schema.sql
--   2. database/grants.sql
--   3. database/policies.sql
--
-- This file is intentionally policy-free so old setup instructions do not
-- recreate legacy policies after policies.sql has cleaned them.
--
-- To assign your first admin after registering:
-- update public.perfiles set role = 'admin' where id = 'TU-UUID-AQUI';
